version: '3.8'

networks:
  ems:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      flyway-migrations:
        condition: service_completed_successfully
      postgresql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/employee_db
    networks:
      ems:
        aliases:
          - app
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - "5901:5901"

  flyway-migrations:
    image: flyway/flyway:10.21.0
    container_name: flyway
    restart: on-failure
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      FLYWAY_URL: jdbc:postgresql://postgresql:5432/employee_db
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: admin
      FLYWAY_LOCATIONS:
    command:
      - migrate
    volumes:
      - ./db/migration:/flyway/sql
    networks:
      - ems

  postgresql:
    image: postgres:17.1
    container_name: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: admins
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresql -d admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ems

volumes:
  ems_data: {}